// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJrtTOm23T_uB-WoEAYWb5JS6RNbx8nc',
    appId: '1:356396839141:web:820e826ea5850318d1e40c',
    messagingSenderId: '356396839141',
    projectId: 'fir-crud-basics-ea659',
    authDomain: 'fir-crud-basics-ea659.firebaseapp.com',
    databaseURL: 'https://fir-crud-basics-ea659-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-basics-ea659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDruuucNiAwj3yzK69ZmThkGxLT-EZ8Ltg',
    appId: '1:356396839141:android:13bc228c961c2ae6d1e40c',
    messagingSenderId: '356396839141',
    projectId: 'fir-crud-basics-ea659',
    databaseURL: 'https://fir-crud-basics-ea659-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-basics-ea659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvFjLfbbetttlZddWA2WDdLbIYAo7DpA',
    appId: '1:356396839141:ios:a90fe25d2f49dcedd1e40c',
    messagingSenderId: '356396839141',
    projectId: 'fir-crud-basics-ea659',
    databaseURL: 'https://fir-crud-basics-ea659-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-basics-ea659.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIvFjLfbbetttlZddWA2WDdLbIYAo7DpA',
    appId: '1:356396839141:ios:a90fe25d2f49dcedd1e40c',
    messagingSenderId: '356396839141',
    projectId: 'fir-crud-basics-ea659',
    databaseURL: 'https://fir-crud-basics-ea659-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-basics-ea659.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZJrtTOm23T_uB-WoEAYWb5JS6RNbx8nc',
    appId: '1:356396839141:web:d5eb7ed3b2727f8ad1e40c',
    messagingSenderId: '356396839141',
    projectId: 'fir-crud-basics-ea659',
    authDomain: 'fir-crud-basics-ea659.firebaseapp.com',
    databaseURL: 'https://fir-crud-basics-ea659-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-basics-ea659.firebasestorage.app',
  );
}
